import java.lang.Exception

fun foo(x: Boolean) {
    try {
        x
    } catch (e: Exception) {
        throw e
    }
}
