import java.lang.Exception

fun foo() {
    try {
        for (i in 1..100) {
        }
    } catch (e: Exception) {
        throw e
    }
}
